package com.example.pesquisa_ia.qualitative;

public enum ActivityCategory {
    AT01_DOCUMENT_ANALYSIS,
    AT02_CONTRACT_ANALYSIS,
    AT03_DATA_ANALYSIS,
    AT04_ANOMALY_DETECTION,
    AT05_FRAUD_IDENTIFICATION,
    AT06_RECONCILIATION,
    AT07_RISK_ASSESSMENT,
    AT08_AUDIT_TESTING,
    AT09_REPORT_GENERATION,
    AT10_RESEARCH_AND_CONSULTATION,
    AT11_AUDIT_PLANNING,
    AT12_OTHER
}
