package com.example.pesquisa_ia.qualitative;

public enum BenefitCategory {
    BE01_PRODUCTIVITY_GAIN,
    BE02_TIME_REDUCTION,
    BE03_AUTOMATION,
    BE04_LARGE_VOLUME_ANALYSIS,
    BE05_PATTERN_ANOMALY_DETECTION,
    BE06_QUALITY_IMPROVEMENT,
    BE07_DECISION_SUPPORT,
    BE08_OPERATIONAL_ERROR_REDUCTION,
    BE09_INFORMATION_ACCESS,
    BE10_PROFESSIONAL_DEVELOPMENT,
    BE11_NO_BENEFIT_IDENTIFIED,
    BE12_OTHER
}
