package com.example.pesquisa_ia.qualitative;

public enum FutureCategory {
    FU01_SUPPORT_TOOL,
    FU02_HUMAN_AI_COLLABORATION,
    FU03_OPERATIONAL_TASK_AUTOMATION,
    FU04_SKILL_TRANSFORMATION,
    FU05_GREATER_ANALYTICAL_FOCUS,
    FU06_HUMAN_SUPERVISION,
    FU07_PARTIAL_ACTIVITY_REPLACEMENT,
    FU08_BROAD_WORK_REPLACEMENT,
    FU09_NEW_PROFESSIONAL_ROLES,
    FU10_UNCERTAINTY,
    FU11_OTHER
}
