package com.example.pesquisa_ia.qualitative;

public enum NonDelegationReasonCategory {
    MN01_PROFESSIONAL_JUDGMENT,
    MN02_PROFESSIONAL_RESPONSIBILITY,
    MN03_COMPLEXITY_CONTEXT,
    MN04_ETHICAL_ISSUES,
    MN05_HUMAN_INTERPRETATION,
    MN06_ERROR_RISK,
    MN07_HUMAN_INTERACTION,
    MN08_CONFIDENTIALITY_SENSITIVITY,
    MN09_REGULATORY_REQUIREMENT,
    MN10_OTHER
}
