package com.example.pesquisa_ia.qualitative;

public enum NonDelegationActivityCategory {
    ND01_PROFESSIONAL_JUDGMENT,
    ND02_AUDIT_CONCLUSION_OPINION,
    ND03_CRITICAL_RISK_ASSESSMENT,
    ND04_MATERIALITY_DECISIONS,
    ND05_EVIDENCE_EVALUATION,
    ND06_CLIENT_COMMUNICATION,
    ND07_COMPLEX_INVESTIGATION,
    ND08_PROFESSIONAL_RESPONSIBILITY_SIGNATURE,
    ND09_ETHICAL_ACTIVITIES,
    ND10_NONE_IDENTIFIED,
    ND11_OTHER
}
