package com.example.pesquisa_ia.qualitative;

public enum RiskCategory {
    RI01_ERRORS_INACCURACY,
    RI02_HALLUCINATION,
    RI03_DATA_PRIVACY,
    RI04_INFORMATION_SECURITY,
    RI05_CONFIDENTIALITY,
    RI06_TECHNOLOGICAL_DEPENDENCY,
    RI07_LACK_OF_TRANSPARENCY,
    RI08_ALGORITHMIC_BIAS,
    RI09_LACK_OF_PROFESSIONAL_JUDGMENT,
    RI10_PROFESSIONAL_RESPONSIBILITY,
    RI11_LACK_OF_KNOWLEDGE,
    RI12_RESULT_RELIABILITY,
    RI13_ETHICAL_ISSUES,
    RI14_COMPLIANCE_REGULATION,
    RI15_COST_INFRASTRUCTURE,
    RI16_RESISTANCE_TO_CHANGE,
    RI17_OTHER
}
